### ISSUE TITLE
nameserver.info type:'CAA' not working

### ISSUE THREAD

**Issue by TheTesla** [inwx/python2.7-client#10]
Looks like filtering queries for CAA records is not working.

**Comment by stv0g** [comment]
According to the XML-RPC documentation, CAA is not a supported record type

**Comment by stv0g** [comment]
@ddmler Has the record type been added to the XML-RPC API?

**Comment by ddmler** [comment]
@stv0g Sorry, it's been added for quite some time, you can just use CAA as recordType like any other: https://www.inwx.de/de/help/apidoc/f/ch03.html#type.recordtype
