### ISSUE TITLE
Is this repository still maintained?

### ISSUE THREAD

**Issue by hhucke** [inwx/python2.7-client#12]
The subject means: if others should invest work into this project would they have a chance to receive a positive answer on a merge request?

Motivation:
The domainrobot module is simply the RPC interface to query information and change parameters but its far from being an object oriented interface. No integrators, no arrays, no nested objects.

**Comment by ddmler** [comment]
We are open for merge requests and are still maintaining this project. However we focus more on our python 3 client than this one and at some point in the future we will deprecate this python 2 client.
